apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    meta.helm.sh/release-name: raycluster
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-09-12T14:09:18Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: raycluster
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: ray-cluster-1.1.1
  name: raycluster-kuberay
  namespace: default
  resourceVersion: "111176"
  uid: 796a02c5-1790-4a32-a5c1-593c12a95bf0
spec:
  headGroupSpec:
    rayStartParams:
      dashboard-host: 0.0.0.0
    serviceType: ClusterIP
    template:
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm
          helm.sh/chart: ray-cluster-1.1.1
      spec:
        affinity: {}
        containers:
        - image: agreatviktor/test-ray-image:latest #The image we want to use
          imagePullPolicy: IfNotPresent
          name: ray-head
          resources:
            limits:
              cpu: "1"
              memory: 4G
            requests:
              cpu: "1"
              memory: 4G
          securityContext: {}
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
        imagePullSecrets: []
        nodeSelector: {}
        tolerations: []
        volumes:
        - emptyDir: {}
          name: log-volume
        - emptyDir: {}
          name: files-volume
  workerGroupSpecs:
  - groupName: workergroup
    maxReplicas: 2
    minReplicas: 1
    numOfHosts: 1
    rayStartParams: {}
    replicas: 1
    template:
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/instance: raycluster
          app.kubernetes.io/managed-by: Helm
          helm.sh/chart: ray-cluster-1.1.1
      spec:
        affinity: {}
        containers:
        - image: agreatviktor/test-ray-image:latest
          imagePullPolicy: IfNotPresent
          name: ray-worker
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: "1"
              memory: 2G
          securityContext: {}
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
        imagePullSecrets: []
        nodeSelector: {}
        tolerations: []
        volumes:
        - emptyDir: {}
          name: log-volume
        - emptyDir: {}
          name: files-volume
status:
  availableWorkerReplicas: 1
  desiredCPU: "2"
  desiredGPU: "0"
  desiredMemory: 3G
  desiredTPU: "0"
  desiredWorkerReplicas: 1
  endpoints:
    client: "10001"
    dashboard: "8265"
    metrics: "8080"
    redis: "6379"
    serve: "8000"
  head:
    podIP: 10.244.0.7
    serviceIP: 10.96.161.95
  lastUpdateTime: "2024-09-13T12:24:27Z"
  maxWorkerReplicas: 2
  minWorkerReplicas: 1
  observedGeneration: 1
  state: ready
