environment: prisoner_guard_env_v0
framework: torch
multi_agent:
  policies:
    prisoner_policy:
      policy_cls: null
      obs_space: 49
      act_space: 4
      config: {}
    guard_policy:
      policy_cls: null
      obs_space: 49
      act_space: 4
      config: {}
  policy_mapping_fn: policy_mapping_fn
training:
  model:
    custom_model: PrisonerGuardModel
resources:
  num_gpus: 0  # This should be dynamically set based on available resources
stop:
  timesteps_total: 100000
checkpoint_freq: 1
storage_path: ~/ray_results/prisoner_guard_env_v0
